@baseUrl = http://localhost:5000

POST {{baseUrl}}/users
content-type: application/json
Authorization: Barear xxx

{
    "name": "John Doe 2",
    "email": "john@example2.com",
    "password": "bcrypt_password"
}

###
GET {{baseUrl}}/users/b1786609-1095-4a52-8729-58b4456281f4
Content-Type: application/json

###
GET {{baseUrl}}/users
Content-Type: application/json

###
PUT {{baseUrl}}/users/b1786609-1095-4a52-8729-58b4456281f4
Content-Type: application/json

{
    "name": "John Doe 1",
    "email": "john@example1.com"
}

###
DELETE {{baseUrl}}/users/0625b873-4dd5-46bf-8ce3-9ffc3fcdeeab
Content-Type: application/json

